### ISSUE TITLE
Editor.openNoteByDate() not working when Date's note doesn't already exist. Create note?

### ISSUE THREAD

**Issue by jgclark** [NotePlan/plugins#180]
At least 4 different devs have hit this one, so I'm marking this as a high priority.

**Comment by jgclark** [comment]
This may be related ... go to a Calendar note for a day that doesn't yet have any content. (_And under the hood no note file_.) Then try a command such as /dayStart that writes to the Editor. It will fail. This is despite the UI showing the reference area contents for that day (where references exist). (Reported 31.12.2021 on Discord bugs.)

**Comment by EduardMe** [comment]
Fixed this in the latest alpha release (729). The issue was that `Editor.note` was nil when the note didn't exist. But you still could do `Editor.content = "something"`. The caveat is now that I had to remove the `does not exist` check, so getting a list of calendar notes also returns cached notes, which have no file yet. They are in the cache, because of calendar events and references. Maybe I can check if it's coming from `Editor.note` vs from `DataStore.calendarnotes`

**Comment by jgclark** [comment]
Fixed the main issue, thanks.
I think the issue it raises will, as you say, really only appear in slightly too high statistics, which is not a big deal.
Closing issue.

**Comment by jgclark** [comment]
I've checked and the count of calendar notes for me has increased by 147 in this new release. That's rather more than I was expecting. So I'm opening this again, though now at a low priority.

**Comment by EduardMe** [comment]
Should be fixed in the next update.

**Comment by dwertheimer** [comment]
Seems to be used in openNoteByFilename but not in openNoteByDate

**Comment by dwertheimer** [comment]
seems to work
