### ISSUE TITLE
How to use node.js package in Noteplan Plugin

### ISSUE THREAD

**Issue by xlicz** [NotePlan/plugins#285]
Hi,I'm a fan of NotePlan, and I'm trying to develop a plugin that connects NotePlan with Airtable. The SDK of airtable can be found at https://github.com/Airtable/airtable.js
The problem is, after tring half a day, I found that it seems we cannot use node js in the NotePlan plugin script. It surprised me because there are lots of node.js packages that will make plugin development lots of easier.
So, please tell me if we can use the node.js package in the plugin? If we can, how to use the node.js package in a plugin?
Bests, Calcus

**Comment by mikeerickson** [comment]
@xlicz Without digging deep into the AirTable API, I can provide a bit of background on how NotePlan supports JavaScript in custom NotePlan Plugins.

First off, NotePlan supports JavaScript through the JavaScriptCode interface, which is a JavaScript Runtime instance, but it is NOT a node instance, and does not support any UI or Browser actions,

In general, NotePlan plugins are able to use npm modules, etc. which do not perform UI related tasks.  For example, if you look at the `package.json` file for the NotePlan Plugin repository, you will see we use a number of npm modules for the various plugins.  

When the plugin is "compiled" using a custom rollup script, the resulting code is a single JavaScript file (`script.js`) and all the modules which may be used are bundled into this single file.

When using JavaScript code in NotePlan, the following conditions must be met:

1. The module must be an npm module
2. The module must not contain code that assumes a browser instance is available, and does not perform UI related operations
3. The module must not make use of any file i/o operations (such as `fs` , `path`, etc node modules)
4. The module must not require node instance

In the case of AirTable, the core implementation assumes it has a browser instance, thus it will not work with NotePlan plugins.  

In reviewing the dependencies from AirTable module, it has at least one that will make the overall module "fail"


```
"node-fetch": "^2.6.7"
```

This module must be used ONLY with node instances, which as mentioned above, NotePlan does not implement a node instance, due to the fact that it uses JavaScriptCode.

**Comment by mikeerickson** [comment]
Explained how NotePlan Plugins are constructed and how npm modules can be used, but they cannot use modules which require a node or browser instance.

**Comment by jgclark** [comment]
This is a very helpful reply, @mikeerickson. 
@dwertheimer, so much so, that I wonder if you could include it next time you're updating the example plugin?

**Comment by mikeerickson** [comment]
@jgclark i will add this to the plugin generator command, as well as add more context in the plugin documentation.   Would save future users some time knowing the limitations.

**Comment by dwertheimer** [comment]
@mikeerickson  If you are going to add this, please except my PR first

**Comment by dwertheimer** [comment]
I agree @mikeerickson this was super helpful. Also @mikeerickson and @xlicz worth looking at this post form @EduardMe https://discord.com/channels/763107030223290449/809886801857871883/980506977807507566

**Comment by dwertheimer** [comment]
@EduardMe Its worth mentioning a lot of this in the NotePlan.co plugin docs.

**Comment by mikeerickson** [comment]
Let’s all be clear, anything other than what we are currently doing via rollup, is gonna change the game.  Until NotePlan supports webview, all other solutions and a non starter. 

Yes, it would be great information to add to all other points of documentation, but making it clear what can and can’t be done in the plugin docs in this repo would be beneficial to those who come here at the request of the plugin documentation on NotePlan.co

**Comment by mikeerickson** [comment]
> @mikeerickson If you are going to add this, please except my PR first

Will do! I am visiting in laws, will be back on Tuesday and will get the PR reviewed/merged.  

My “updates” are more planned for documentation, and likely go more into detail on how rollup is used.

**Comment by nmn** [comment]
@xlicz i looked at air table.js and as mentioned before the only ‘node’ dependency it relies on is `node-fetch`.

turns out `node-fetch` is just a polyfill for the fetch API that should supported within the Noteplan plugin API, so it should relatively easy to make a small fork of the airtable SDK that will work as expected.

**Comment by mikeerickson** [comment]
@nmn well, then get to work on the east fork and make it happen.  I would be curious to see just how easy it is.

**Comment by xlicz** [comment]
@mikeerickson @jgclark @nmn @dwertheimer 
Thank you all the guys for the nice reply! I love NotePlan even more because of you great developers!

1. It would be great to add detailed documents about how to use the node.js module in NotePlan plugins, on help.noteplan.co plugin docs, because I did read every document in noteplan.co carefully but cannot find relevant information. To offer you some detailed suggestions, you may consider including some problems that I faced: 
    a. whether or not can we use the standard node.js module; 
    b. how to use it? -- from where to download the package? modify which plugin files? how to modify plugin files so the plugin code can access the node.js module code. 
   The problem that I faced is starting with the error message "Can't find variable: require"(cannot find node environment/codes are not run by node instance), and doing lots of guessing and testing, and finally things did not work.
3. It would be even better to show a step-to-step plugin development example that uses a standard node.js module.
4. I think the ability to use the standard node.js module is essentially important, for example I'm also considering connecting notion to NotePlan, which also needs to use a Notion node.js module https://github.com/makenotion/notion-sdk-js.
5. small points: 
    https://help.noteplan.co/article/67-create-command-bar-plugins   links to   https://help.noteplan.co/article/103-debugging-plugins , which is not working,  you may consider to fix it.

4| Can't find variable: require

**Comment by xlicz** [comment]
> I agree @mikeerickson this was super helpful. Also @mikeerickson and @xlicz worth looking at this post form @EduardMe https://discord.com/channels/763107030223290449/809886801857871883/980506977807507566

It seems the channel has access control, I cannot see it.

**Comment by nmn** [comment]
> @nmn well, then get to work on the easy fork and make it happen. I would be curious to see just how easy it is. 😊

Here's my fork that should work: https://github.com/nmn/airtable.js

**Comment by dwertheimer** [comment]
@nmn So how would someone import and use your fork? I looked at the file in the build directory and at the very top, it seems to be looking for "window". Is this not the file that you were importing? I would be curious if you tested it and found it to work.

**Comment by EduardMe** [comment]
@dwertheimer You pointed to a Discord message which I also can't seem to open. Do you mean my comment of using browserify to rollup/convert node modules? I didn't write a help article on this because I didn't try it myself, does anyone have good experiences with this?

@xlicz Here's a link how to make it work with browserify: https://blog.risingstack.com/running-node-modules-in-your-ios-project/

**Comment by nmn** [comment]
@EduardMe those projects for running Node within iOS are all abandoned.

@dwertheimer NPM lets you install dependencies from github URLs directly. You can add

```json
"dependencies": {
    "airtable": "nmn/airtable",
}
```

and it should pull my fork while my PR's in review.

**Comment by dwertheimer** [comment]
Yes that's what I was thinking after reading your post. Not sure that it
works. @mikeerickson seems to think it won't.
