### ISSUE TITLE
/int doesn't work for Daily Notes

### ISSUE THREAD

**Issue by renehuber** [NotePlan/plugins#31]
If understood correctly, /int should add a task to the Today's calendar note - if not configured otherwise.
But for me, when `inboxFilename` is "", then nothing happends. Looking at the code, there is no handling of "".

Something like this:
(Sorry, not a developer)
``` 
// quickCapture.js:284
if (pref_inboxFilename == '') {
    inboxNote = DataStore.calendarNoteByDate()
}
```

**Comment by dwertheimer** [comment]
@jgclark I think @renehuber has found a couple of issues. The README says
`- /int: Quickly add a task to your '📥 Inbox' note (defaults to Daily note, but can be configured to a different specific one)`

But there is no code to default to the Daily note.
1) If you don't have a configuration file or don't have `inbox` in your configuration, then the command gracefully exits (though you can't read the message because of the font size issue you and @EduardMe have discussed). Based on the plugin's description, I wouldn't expect it to exit if there's no `inbox` (should default to the daily Calendar note)
2) If on the other hand, you have an `inbox` specified, but inboxFilename is not set or set to '', then the script will run, will ask you for a task, but put it nowhere (because the ask-for-task in 235-238 is outside of the if/then blocks). In this case as well, I think you fall back to the daily calendar note. Should be able to do both of those use cases at the same time.

**Comment by kuochang** [comment]
> If understood correctly, /int should add a task to the Today's calendar note - if not configured otherwise.
> But for me, when `inboxFilename` is "", then nothing happends. Looking at the code, there is no handling of "".
> 
> Something like this:
> (Sorry, not a developer)
> 
> ```
> // quickCapture.js:284
> if (pref_inboxFilename == '') {
>     inboxNote = DataStore.calendarNoteByDate()
> }
> ```

I face the same issue. I followed the instruction by leaving inboxfilename blank, but nothing happens in my today's daily note...

**Comment by jgclark** [comment]
I've now released an update to Quick Capture plugin that hopefully addresses this problem.

**Comment by renehuber** [comment]
Thank you, @jgclark! Just updated and it works.
