### ISSUE TITLE
jgclark.RepeatExtensions doesn't work well

### ISSUE THREAD

**Issue by DHERRADOR** [NotePlan/plugins#419]
I try use the [Running Automatically](https://github.com/NotePlan/plugins/tree/main/jgclark.RepeatExtensions/#running-it-automatically) function of the plugin **RepeatExtensions**, but it doesn't generate the new task correctly.

Also doesn't work the command `/rpt`, that does the same effect.

I hope this video can helps to solve the bug.

https://user-images.githubusercontent.com/1575263/223662374-b4cca755-3c07-4f53-b480-8820feaa500c.mov

**Comment by jgclark** [comment]
Thanks.
I can see something unexpected in the first third of the video: the `>` shouldn't appear on its own.
This is what I get in a similar situation:
![CleanShot 2023-03-08 at 18 25 30](https://user-images.githubusercontent.com/1671754/223801692-9cbaf08d-7845-4bff-a660-fbd568be7d93.png)

So please send me the logs so I can work out what's different for you. Please also do the usual: which version of NP are you running, and in this case (just in case its relevant) please indicate what your Mac's language and time zone are set to.

I'm not sure what you were trying to show in the rest of the video, perhaps because the cursor goes off the recorded area. Clicking on the `@repeat(+2m)` isn't going to do anything other than take you to the list of identical mentions.

**Comment by DHERRADOR** [comment]
I have the last version of NP.
What I want to show at the end of the video is that clicking on the tag @repeat, you can see that the plugin didn’t create any other copy of the task in other different day.

It’s important that you note that the plugin also fail even with the command `/rpt`.

I’ll send you the logs.

**Comment by DHERRADOR** [comment]
Could you please send me an email to attack you the logs. 
I would prefer not to share it here.

**Comment by DHERRADOR** [comment]
Here you have the logs.

[np-error.log](https://github.com/NotePlan/plugins/files/10943985/np-error.log)
[np-out 2.log](https://github.com/NotePlan/plugins/files/10943989/np-out.2.log)
[np-out.log](https://github.com/NotePlan/plugins/files/10943990/np-out.log)

**Comment by jgclark** [comment]
> Here you have the logs.

Sorry, I can't be expected to wade through more than 610,000 lines of logs.

Here's the guidance on how to give us useful logs:

Please include version of NP you’re running (not just ‘latest’) and the plugin console logs for that specific command run. To do this:
- set the log level to DEBUG in the plugin’s settings.
- open console log (last item in the Help menu). 
- Please make a separate text file of them, and then attach to the Discord thread or GitHub issue.
- If they contain sensitive phrases please remove that part of the lines first.

You can send logs to thejgc at gmail instead of attaching here.

**Comment by DHERRADOR** [comment]
Dear ClarkReally I would do what you want. But I have no a clear idea what are you asking me. Could you give me a more detailed instructions. Or a short video of what you want I do?Sorry. El 11 mar 2023, a las 16:17, Jonathan Clark ***@***.***> escribió:﻿

Here you have the logs.

Sorry, I can't be expected to wade through more than 610,000 lines of logs.
Here's the guidance on how to give us useful logs:
Please include version of NP you’re running (not just ‘latest’) and the plugin console logs for that specific command run. To do this:

set the log level to DEBUG in the plugin’s settings.
open console log (last item in the Help menu).
Please make a separate text file of them, and then attach to the Discord thread or GitHub issue.
If they contain sensitive phrases please remove that part of the lines first.

You can send logs to thejgc at gmail instead of attaching here.

**Comment by jgclark** [comment]
Preferences > Plugins > Repeat > Log level = DEBUG
Help > Plugin Console
Run command
Send me logs from console

**Comment by dbcoyer** [comment]
Hi @jgclark 
Just wanted to report I’m seeing the same thing as he shows in the video. I’m not at my desktop; I’ll get you some logs when I get there. I just came here to report this issue and saw that it has already been reported.
Thanks.

**Comment by jgclark** [comment]
OK, I've done some more testing, and now found for myself what you're reporting @dbcoyer and @DHERRADOR. Stay tuned for a fix.

**Comment by dbcoyer** [comment]
That’s great. Let me know if you need anything from me.

**Comment by DHERRADOR** [comment]
Thanks very much jgclark.Sorry but this week my job doesn’t allow me to send you the logs. I was work yesterday since 8:00h until 22:00h. I’ll test your solution and  will came back with a feedback. Best Regards. El 15 mar 2023, a las 1:08, dbcoyer ***@***.***> escribió:﻿
That’s great. Let me know if you need anything from me.

**Comment by jgclark** [comment]
> That’s great. Let me know if you need anything from me.

Thanks: please let me know whether the new release fixes the issue.

**Comment by DHERRADOR** [comment]
Yes. Thanks. It’s solved. You did a good job. El 15 mar 2023, a las 16:39, Jonathan Clark ***@***.***> escribió:﻿

That’s great. Let me know if you need anything from me.

Thanks: please let me know whether the new release fixes the issue.

**Comment by dbcoyer** [comment]
Yes, it is working now for me. Thank you for your quick response on this very helpful plugin.
