### ISSUE TITLE
Fixing bug in getDateStringFromCalendarFilename

### ISSUE THREAD

**Issue by jgclark** [NotePlan/plugins#431]
I think I've got something wrong in the tests for `getDateStringFromCalendarFilename()` in dateTime.js. I seem to have treated weekly notes different from the others. So some of the tests are passing for example "2022-W52.md" → "20221226". This is essentially a conversion from weekly to daily date.  That's a valid thing to do, but its not what the docs for this particular function say.  The other time periods work as the docs suggest, e.g. "2023-Q2.md" → "2023-Q2".

The PR that's hopefully attached to this resolves this. But asking for review in case in your use of this in NPTimeblocking.js you rely on the unintended weekly → daily conversion.

**Comment by jgclark** [comment]
@dwertheimer can you review this? I seem to have pushed rather than create a PR, sorry.

**Comment by jgclark** [comment]
Nudging @dwertheimer ... it would be nice to finish this one off. Thanks.

**Comment by dwertheimer** [comment]
I have to say that I'm confused by this function that apparently I wrote. 
I don't understand why we would want it to return an unhyphenated date. Feels like it always should have returned a hyphenated date. But the tests show unhyphenated, so that must be what I was thinking at the time (I don't know why)

It does feel like this could/should lead to problems in my plugin, but the changes you made shouldn't negatively affect me. So I am going to close this because your change should be fine. Thanks @jgclark

**Comment by jgclark** [comment]
Thanks, @dwertheimer.
FYI unhyphenated dates are necessary when working at the file (not note) level.
