### ISSUE TITLE
ensureFrontmatter() failing for calendar notes [from template]

### ISSUE THREAD

**Issue by jgclark** [NotePlan/plugins#543]
**Checks**
- [x] I confirm I have restarted NotePlan and this problem still persists.
- [x] Is this a repeatable problem?

**Describe the bug**
NPFrontMatter's ensureFrontmatter() doesn't do anything to calendar notes without existing frontmatter, at least when run from a Template.

**To Reproduce**
I discovered this because NoteHelpers' new addTriggerToNote() command isn't working when run from this Template:

```markdown
---
title: Test addTriggerToNote
type: test
---
✅
<% await DataStore.invokePluginCommandByName("add trigger to note","jgclark.NoteHelpers",["onEditorWillSave => jgclark.Dashboard.decideWhetherToUpdateDashboard"]); -%>
```

**System**
 - NotePlan Version 3.10.2 b1171
 - NoteHelpers 0.19.1

**Additional context**
The same command _does_ work when run interactively.

I have pushed a slightly updated copy of NPFrontMatter.js that includes a little more logging, and FIXME where I think the problem is. Please see if you can reproduce and fix.

**Comment by dwertheimer** [comment]
@jgclark BTW, beyond that, as mentioned in #540, this is almost certainly a race condition caused by the age-old issue of Editor.note vs. Editor. Templating is acting on Editor, and your calls may be passing Editor.note and so my guess is that the note gets written correctly and then overwritten by the template because of this conflict.
Maybe check Versions on the note to see if this is true

**Comment by jgclark** [comment]
I've made some changes to NPFrontMatter helpers to deal with more edge cases.
And changed from Editor.note to Editor in at least one place.
Appears to be all fixed, and so will commit the changes shortly.
