### ISSUE TITLE
Dashboard feature: remove date on move

### ISSUE THREAD

**Issue by dwertheimer** [NotePlan/plugins#549]
I have tasks with >dates. When I move those tasks to a day (e.g. today or tomorrow), I think the >date should be removed. As it stands, it does move the task but leaves the overdue date, which keeps it in the "overdue" section

![Screen Cap 2024-04-04 at 13 30 30@2x](https://github.com/NotePlan/plugins/assets/8949588/2234bf04-6e7d-4c90-8fb1-0b1578cc405b)

Please just put this somewhere on your list. Thanks!

**Comment by SirTristam** [comment]
I've analyzed this and determined where this is happening. It only occurs when moving tasks between calendar notes or from a project note to a calendar note, not when rescheduling in place. Rescheduling in place properly removes the previously scheduled date when using the quick edit dialog pictured above.

This issue is similar to (but not the same) as the issue reported in Discord at https://discord.com/channels/763107030223290449/1111377470038491146/1232038750742384721. In the Discord report, the schedule date is not removed from tasks when they are rescheduled in place using the 'All -> Today' button in the Overdue section.

I am looking at scheduled date handling for all rescheduling actions, and will shortly have a pull request for **both the Dashboard and the DashboardReact plugins** to address the following issues:

1. When moving tasks instead of rescheduling in place, scheduled dates are not removed from tasks when moved from a calendar note or project note to the new calendar note using any of the scheduling buttons in the quick edit dialog (specifically reported as this issue).
2. When rescheduling in place, scheduled dates for weeks, months, quarters, and years are not removed from tasks using the 'All -> Today' button in the Overdue section of the Dashboard (reported on Discord at above link).

If additional failures to remove previously scheduled dates when rescheduling or moving tasks are discovered during this process, they will be included and documented.

**Comment by jgclark** [comment]
@SirTristam thanks so much for working on this, and figuring out the complexity of the many possibilities that the Dashboard has to cover. I look forward to your PR(s) when ready.

**Comment by jgclark** [comment]
@SirTristam any news on this? The reason I ask is that the React codebase is changing quite rapidly at the moment, and will do so for the next week at least. So I'm keen to integrate your changes before it potentially is more complicated to do so. Thanks.

**Comment by SirTristam** [comment]
@jgclark I've submitted a PR for this. I've noted the different scenarios that were not working properly in the description of the PR. 

Running down the different scenarios for this, I wound up down a bit of a rabbit hole from one of my tests, but it's not directly related to this and can wait until after the React refactor. (Basically, I found that if you have a task on Today's calendar note, and you schedule it with either >today or >today's date, it will not show up in the Today section of the dashboard. But since a user has to manually do this, and the todo will show up on the dashboard the next day, it's not worth cleaning up right now.)
